# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d7f8dd76c14b02cd23add6f0d28ff991403f05798f117e1bc8292fe0c567c8c844f046f0e35bb4bff5dc4906899a186cda2a497b091cb4cf724e6a91c61bd4

test:
  secret_key_base: c4b8d90cfef90bcc499de044c49c730abbbceed55de24a687bf7115bbc498d53c829a791e808f2112da46cb5df98b3650dd4e9e17aed4b5c16e56f8f8e39e198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
